services:
  paradise-helper-app:
    image: ghcr.io/Ne0shka/paradise-helper-app:latest
    container_name: paradise-helper-app
    restart: always
    environment:
      API_ID: "0"
      API_HASH: "123abc"
      BOT_TOKEN: "0:123abc"
    volumes:
      - ./bot.session:/app/bot.session